// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi MobileApi
Backend assignment MobileApi spec


    Schemes:
      http
      https
    Host: localhost:8000
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
