// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Backend assignment MobileApi spec",
    "title": "MobileApi",
    "version": "1.0.0"
  },
  "host": "localhost:8000",
  "basePath": "/v1",
  "paths": {
    "/articles/{articleId}": {
      "get": {
        "description": "Gets article details such as the body",
        "summary": "Get article details",
        "parameters": [
          {
            "type": "string",
            "description": "The article's id",
            "name": "articleId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Article details including overview and body",
            "schema": {
              "$ref": "#/definitions/Article"
            }
          },
          "404": {
            "description": "Requested article does not exist",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      },
      "patch": {
        "description": "Updates article's starred property",
        "summary": "Updates article's starred property",
        "parameters": [
          {
            "type": "string",
            "description": "The article's id",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "name": "SetStarredRequest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "starred": {
                  "type": "boolean"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Starred property updated OK",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "404": {
            "description": "Requested category does not exist",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "description": "Returns a list containing all article categories",
        "summary": "Gets article categories",
        "responses": {
          "200": {
            "description": "A list of Category objects",
            "schema": {
              "$ref": "#/definitions/ListCategoriesResponse"
            }
          }
        }
      }
    },
    "/categories/{categoryId}": {
      "get": {
        "description": "Gets all the articles for an category",
        "summary": "Gets category articles",
        "parameters": [
          {
            "type": "string",
            "description": "The category's id",
            "name": "categoryId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of Article overview objects",
            "schema": {
              "$ref": "#/definitions/ListArticlesResponse"
            }
          },
          "404": {
            "description": "Requested category does not exist",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Article": {
      "type": "object",
      "required": [
        "overview",
        "body",
        "imageUrl"
      ],
      "properties": {
        "body": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "overview": {
          "$ref": "#/definitions/ArticleOverview"
        }
      }
    },
    "ArticleOverview": {
      "type": "object",
      "required": [
        "id",
        "title",
        "source",
        "starred",
        "timestamp"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "starred": {
          "type": "boolean"
        },
        "timestamp": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Category": {
      "type": "object",
      "required": [
        "id",
        "title",
        "imageUrl"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "ListArticlesResponse": {
      "type": "object",
      "required": [
        "articles"
      ],
      "properties": {
        "articles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ArticleOverview"
          }
        }
      }
    },
    "ListCategoriesResponse": {
      "type": "object",
      "required": [
        "categories"
      ],
      "properties": {
        "categories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Category"
          }
        }
      }
    },
    "Response": {
      "type": "object",
      "required": [
        "status"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Backend assignment MobileApi spec",
    "title": "MobileApi",
    "version": "1.0.0"
  },
  "host": "localhost:8000",
  "basePath": "/v1",
  "paths": {
    "/articles/{articleId}": {
      "get": {
        "description": "Gets article details such as the body",
        "summary": "Get article details",
        "parameters": [
          {
            "type": "string",
            "description": "The article's id",
            "name": "articleId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Article details including overview and body",
            "schema": {
              "$ref": "#/definitions/Article"
            }
          },
          "404": {
            "description": "Requested article does not exist",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      },
      "patch": {
        "description": "Updates article's starred property",
        "summary": "Updates article's starred property",
        "parameters": [
          {
            "type": "string",
            "description": "The article's id",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "name": "SetStarredRequest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "starred": {
                  "type": "boolean"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Starred property updated OK",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "404": {
            "description": "Requested category does not exist",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "description": "Returns a list containing all article categories",
        "summary": "Gets article categories",
        "responses": {
          "200": {
            "description": "A list of Category objects",
            "schema": {
              "$ref": "#/definitions/ListCategoriesResponse"
            }
          }
        }
      }
    },
    "/categories/{categoryId}": {
      "get": {
        "description": "Gets all the articles for an category",
        "summary": "Gets category articles",
        "parameters": [
          {
            "type": "string",
            "description": "The category's id",
            "name": "categoryId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of Article overview objects",
            "schema": {
              "$ref": "#/definitions/ListArticlesResponse"
            }
          },
          "404": {
            "description": "Requested category does not exist",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Article": {
      "type": "object",
      "required": [
        "overview",
        "body",
        "imageUrl"
      ],
      "properties": {
        "body": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "overview": {
          "$ref": "#/definitions/ArticleOverview"
        }
      }
    },
    "ArticleOverview": {
      "type": "object",
      "required": [
        "id",
        "title",
        "source",
        "starred",
        "timestamp"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "starred": {
          "type": "boolean"
        },
        "timestamp": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Category": {
      "type": "object",
      "required": [
        "id",
        "title",
        "imageUrl"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "ListArticlesResponse": {
      "type": "object",
      "required": [
        "articles"
      ],
      "properties": {
        "articles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ArticleOverview"
          }
        }
      }
    },
    "ListCategoriesResponse": {
      "type": "object",
      "required": [
        "categories"
      ],
      "properties": {
        "categories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Category"
          }
        }
      }
    },
    "Response": {
      "type": "object",
      "required": [
        "status"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  }
}`))
}
