// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCategoriesCategoryIDParams creates a new GetCategoriesCategoryIDParams object
// no default values defined in spec.
func NewGetCategoriesCategoryIDParams() GetCategoriesCategoryIDParams {

	return GetCategoriesCategoryIDParams{}
}

// GetCategoriesCategoryIDParams contains all the bound params for the get categories category ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCategoriesCategoryID
type GetCategoriesCategoryIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The category's id
	  Required: true
	  In: path
	*/
	CategoryID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCategoriesCategoryIDParams() beforehand.
func (o *GetCategoriesCategoryIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCategoryID, rhkCategoryID, _ := route.Params.GetOK("categoryId")
	if err := o.bindCategoryID(rCategoryID, rhkCategoryID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCategoryID binds and validates parameter CategoryID from path.
func (o *GetCategoriesCategoryIDParams) bindCategoryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CategoryID = raw

	return nil
}
