// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mobileService/models"
)

// GetCategoriesCategoryIDOKCode is the HTTP code returned for type GetCategoriesCategoryIDOK
const GetCategoriesCategoryIDOKCode int = 200

/*GetCategoriesCategoryIDOK A list of Article overview objects

swagger:response getCategoriesCategoryIdOK
*/
type GetCategoriesCategoryIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListArticlesResponse `json:"body,omitempty"`
}

// NewGetCategoriesCategoryIDOK creates GetCategoriesCategoryIDOK with default headers values
func NewGetCategoriesCategoryIDOK() *GetCategoriesCategoryIDOK {

	return &GetCategoriesCategoryIDOK{}
}

// WithPayload adds the payload to the get categories category Id o k response
func (o *GetCategoriesCategoryIDOK) WithPayload(payload *models.ListArticlesResponse) *GetCategoriesCategoryIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get categories category Id o k response
func (o *GetCategoriesCategoryIDOK) SetPayload(payload *models.ListArticlesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoriesCategoryIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCategoriesCategoryIDNotFoundCode is the HTTP code returned for type GetCategoriesCategoryIDNotFound
const GetCategoriesCategoryIDNotFoundCode int = 404

/*GetCategoriesCategoryIDNotFound Requested category does not exist

swagger:response getCategoriesCategoryIdNotFound
*/
type GetCategoriesCategoryIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetCategoriesCategoryIDNotFound creates GetCategoriesCategoryIDNotFound with default headers values
func NewGetCategoriesCategoryIDNotFound() *GetCategoriesCategoryIDNotFound {

	return &GetCategoriesCategoryIDNotFound{}
}

// WithPayload adds the payload to the get categories category Id not found response
func (o *GetCategoriesCategoryIDNotFound) WithPayload(payload *models.Response) *GetCategoriesCategoryIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get categories category Id not found response
func (o *GetCategoriesCategoryIDNotFound) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoriesCategoryIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
