// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mobileService/models"
)

// GetCategoriesOKCode is the HTTP code returned for type GetCategoriesOK
const GetCategoriesOKCode int = 200

/*GetCategoriesOK A list of Category objects

swagger:response getCategoriesOK
*/
type GetCategoriesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListCategoriesResponse `json:"body,omitempty"`
}

// NewGetCategoriesOK creates GetCategoriesOK with default headers values
func NewGetCategoriesOK() *GetCategoriesOK {

	return &GetCategoriesOK{}
}

// WithPayload adds the payload to the get categories o k response
func (o *GetCategoriesOK) WithPayload(payload *models.ListCategoriesResponse) *GetCategoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get categories o k response
func (o *GetCategoriesOK) SetPayload(payload *models.ListCategoriesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
