// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// PatchArticlesArticleIDHandlerFunc turns a function with the right signature into a patch articles article ID handler
type PatchArticlesArticleIDHandlerFunc func(PatchArticlesArticleIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchArticlesArticleIDHandlerFunc) Handle(params PatchArticlesArticleIDParams) middleware.Responder {
	return fn(params)
}

// PatchArticlesArticleIDHandler interface for that can handle valid patch articles article ID params
type PatchArticlesArticleIDHandler interface {
	Handle(PatchArticlesArticleIDParams) middleware.Responder
}

// NewPatchArticlesArticleID creates a new http.Handler for the patch articles article ID operation
func NewPatchArticlesArticleID(ctx *middleware.Context, handler PatchArticlesArticleIDHandler) *PatchArticlesArticleID {
	return &PatchArticlesArticleID{Context: ctx, Handler: handler}
}

/*PatchArticlesArticleID swagger:route PATCH /articles/{articleId} patchArticlesArticleId

Updates article's starred property

Updates article's starred property

*/
type PatchArticlesArticleID struct {
	Context *middleware.Context
	Handler PatchArticlesArticleIDHandler
}

func (o *PatchArticlesArticleID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchArticlesArticleIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PatchArticlesArticleIDBody patch articles article ID body
// swagger:model PatchArticlesArticleIDBody
type PatchArticlesArticleIDBody struct {

	// starred
	Starred bool `json:"starred,omitempty"`
}

// Validate validates this patch articles article ID body
func (o *PatchArticlesArticleIDBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PatchArticlesArticleIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchArticlesArticleIDBody) UnmarshalBinary(b []byte) error {
	var res PatchArticlesArticleIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
