// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPatchArticlesArticleIDParams creates a new PatchArticlesArticleIDParams object
// no default values defined in spec.
func NewPatchArticlesArticleIDParams() PatchArticlesArticleIDParams {

	return PatchArticlesArticleIDParams{}
}

// PatchArticlesArticleIDParams contains all the bound params for the patch articles article ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchArticlesArticleID
type PatchArticlesArticleIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	SetStarredRequest PatchArticlesArticleIDBody
	/*The article's id
	  Required: true
	  In: path
	*/
	ArticleID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchArticlesArticleIDParams() beforehand.
func (o *PatchArticlesArticleIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PatchArticlesArticleIDBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("setStarredRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("setStarredRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.SetStarredRequest = body
			}
		}
	} else {
		res = append(res, errors.Required("setStarredRequest", "body"))
	}
	rArticleID, rhkArticleID, _ := route.Params.GetOK("articleId")
	if err := o.bindArticleID(rArticleID, rhkArticleID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindArticleID binds and validates parameter ArticleID from path.
func (o *PatchArticlesArticleIDParams) bindArticleID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ArticleID = raw

	return nil
}
